version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: zsksample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
<<<<<<< HEAD
      - 5432:5432
=======
      - 5432:5432
>>>>>>> 9586a77f9da9fc4c54fc627604d5aa161f68d2db
